#!/bin/bash

hexo clean
rm -rf assets/quasar-play
mkdir -p assets/quasar-play
mkdir -p assets/quasar-play/android
mkdir -p assets/quasar-play/apple
cd /work/quasar-play; npm run clean; npm run build:mat; cp -R dist/* /work/quasar-framework.org/assets/quasar-play/android/
npm run clean; npm run build:ios; cp -R dist/* /work/quasar-framework.org/assets/quasar-play/apple/; cd /work/quasar-framework.org
node node_modules/gulp/bin/gulp.js variables
hexo generate
node node_modules/gulp/bin/gulp.js
